name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main, sang53-patch-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i -P

      - name: Build project
        run: pnpm build

      - name: Deploy to deploy branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan deploy
          git rm -rf .
          mv dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin deploy
